- title: true
- shields:
    style: 'flat-square'
    shields:
      - alt: 'flipactual'
        image: 'badge/😋-flipactual-218AC7.svg'
        link: 'https://www.flipactual.com/'
      - alt: 'Travis'
        image: 'travis/flipactual/www.stupid.cards.svg'
        link: 'https://travis-ci.org/flipactual/www.stupid.cards/'
- include: './docs/scripts.md'
- license: true
